### ISSUE TITLE
Feature request: Fahrenheit

### ISSUE THREAD

**Issue by kanetik** [zopieux/mugctl#2]
Would be awesome if I could see the current temp and set temp in Fahrenheit! This web app blows my mind, I had no idea web apps could pair with BT devices!

**Comment by kanetik** [comment]
Side question - should I expect the web app to have to re-pair pretty much every time I use it? I would have expected (especially if I added it to my launcher like it prompts) that it would keep the pairing, but it does not. It's much more straightforward to pair than to the awful Ember app, but just feels like it shouldn't be necessary, so I'm wondering if I am doing something wrong...

**Comment by zopieux** [comment]
>Would be awesome if I could see the current temp and set temp in Fahrenheit!

I can try to do that in the upcoming weeks.

>This web app blows my mind, I had no idea web apps could pair with BT devices!

Me too until I tried :-) Thanks for the kind words.

>I would have expected (especially if I added it to my launcher like it prompts) that it would keep the pairing, but it does not.

Yeah, I know. I believe this is a technical limitation of the Bluetooth stack exposed by the Chrome JS API. In other words, it's not in my power to make it pair automatically. I agree it is annoying and I'll make the change if this ever becomes possible, but I think it's acceptable because I only need to pair once in a while to change my preferred temperature or color, to be honest.

**Comment by kanetik** [comment]
👍
